const ANALYTICAL_BLUE_SCALE = ["#0f4fe6", "#1f60f4", "#2f73ff", "#5190ff", "#79adff", "#aacbff"];
const ANALYTICAL_BLUE_STRONG = ["#0b42c8", "#1252df", "#1f60f4", "#2f73ff", "#5190ff", "#73abff"];

const ANALYTICAL_BLUE_DEEP = "#0f4fe6";
const ANALYTICAL_BLUE_ACCENT = "#1f60f4";
const ANALYTICAL_BLUE_MID = "#4b88ff";
const ANALYTICAL_BLUE_SOFT = "#79adff";
const ANALYTICAL_BLUE_PALE = "#aacbff";
const ANALYTICAL_BLUE_FAINT = "#dceaff";

export {
  ANALYTICAL_BLUE_ACCENT,
  ANALYTICAL_BLUE_DEEP,
  ANALYTICAL_BLUE_FAINT,
  ANALYTICAL_BLUE_MID,
  ANALYTICAL_BLUE_PALE,
  ANALYTICAL_BLUE_SCALE,
  ANALYTICAL_BLUE_SOFT,
  ANALYTICAL_BLUE_STRONG,
};
